name: SwiftBoilerplate
configs:
  Debug: debug
  Develop: develop
  Staging: staging
  Release: release
options:
  bundleIdPrefix: Masanao-Imai
  deploymentTarget:
    iOS: '13.0'
settings:
  base:
    SWIFT_VERSION: 5.0
    PRODUCT_NAME: $TARGET_NAME
    CURRENT_PROJECT_VERSION: 1
schemes:
  SwiftBoilerplate:
    build:
      targets:
        SwiftBoilerplate: all
        SwiftBoilerplateTests: [test]
        SwiftBoilerplateUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Develop
    analyze:
      config: Develop
    archive:
      config: Develop
  SwiftBoilerplate-staging:
    build:
      targets:
        SwiftBoilerplate: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Staging
    analyze:
      config: Debug
    archive:
      config: Staging
  SwiftBoilerplate-store:
    build:
      targets:
        SwiftBoilerplate: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
targets:
  SwiftBoilerplate:
    type: application
    platform: iOS
    sources: SwiftBoilerplate
    settings:
      CODE_SIGN_STYLE: Manual
      INFOPLIST_FILE: SwiftBoilerplate/Info.plist
    configs:
      Debug:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        CODE_SIGN_IDENTITY: iPhone Developer
        DEVELOPMENT_TEAM: K82438J7JC
        PRODUCT_BUNDLE_IDENTIFIER: Masanao-Imai.SwiftBoilerplate
        PRODUCT_NAME: $TARGET_NAME
      Develop:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEVELOP
        CODE_SIGN_IDENTITY: iPhone Distribution
        DEVELOPMENT_TEAM: K82438J7JC
        PRODUCT_BUNDLE_IDENTIFIER: Masanao-Imai.SwiftBoilerplate
        PRODUCT_NAME: $TARGET_NAME
      Staging:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: STAGING
        CODE_SIGN_IDENTITY: iPhone Distribution
        DEVELOPMENT_TEAM: K82438J7JC
        PRODUCT_BUNDLE_IDENTIFIER: Masanao-Imai.SwiftBoilerplate
        PRODUCT_NAME: $TARGET_NAME
      Release:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
        CODE_SIGN_IDENTITY: iPhone Distribution
        PRODUCT_BUNDLE_IDENTIFIER: Masanao-Imai.SwiftBoilerplate
        PRODUCT_NAME: $TARGET_NAME
    scheme:
      testTargets:
        - SwiftBoilerplateTests
        - SwiftBoilerplateUITests
    prebuildScripts:
      - name: Run SwiftFormat
        script: |
          if which mint >/dev/null; then
          mint run swiftformat swiftformat .
          else
          echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
          fi
      - name: Run SwiftLint
        script: |
          if which mint >/dev/null; then
          mint run swiftlint swiftlint
          else
          echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
          fi
      - name: Run SwiftGen
        script: |
          if which mint >/dev/null; then
          mint run swiftgen swiftgen
          else
          echo "warning: Mint not installed, download from https://github.com/yonaskolb/Mint"
          fi
  SwiftBoilerplateTests:
    type: bundle.unit-test
    platform: iOS
    sources: SwiftBoilerplateTests
    dependencies:
      - target: SwiftBoilerplate
  SwiftBoilerplateUITests:
    type: bundle.ui-testing
    platform: iOS
    sources: SwiftBoilerplateUITests
    dependencies:
      - target: SwiftBoilerplate
